language: node_js
node_js:
  - lts/*
install: npm install
script: make public
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "kygovbook"
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-east-2